from enum import StrEnum


FRAUD_EVENTS_COLLECTION = "fraud_events"
BLOCKED_ENTITIES_COLLECTION = "blocked_entities"


class FraudEventType(StrEnum):
    NEW_IP_FOR_FINGERPRINT = "NEW_IP_FOR_FINGERPRINT"
    COOKIE_MISSING_BUT_FINGERPRINT_MATCHED = "COOKIE_MISSING_BUT_FINGERPRINT_MATCHED"
    LOCAL_STORAGE_CHANGED = "LOCAL_STORAGE_CHANGED"
    SESSION_CHANGED = "SESSION_CHANGED"
    MULTIPLE_IPS_DETECTED = "MULTIPLE_IPS_DETECTED"
    TOO_MANY_SESSIONS = "TOO_MANY_SESSIONS"
    VPN_PROXY_SUSPECTED = "VPN_PROXY_SUSPECTED"
    FREE_LIMIT_REACHED = "FREE_LIMIT_REACHED"
    BLOCKED_VISITOR_REQUEST = "BLOCKED_VISITOR_REQUEST"
    SUSPICIOUS_REIDENTIFICATION = "SUSPICIOUS_REIDENTIFICATION"


class FraudSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class BlockedEntityType(StrEnum):
    FINGERPRINT = "FINGERPRINT"
    IP = "IP"
    COOKIE = "COOKIE"
    LOCAL_STORAGE = "LOCAL_STORAGE"
    VISITOR = "VISITOR"
