from enum import StrEnum


FRAUD_EVENTS_COLLECTION = "fraud_events"
ADMIN_AUDIT_LOGS_COLLECTION = "admin_audit_logs"


class FraudEventType(StrEnum):
    VISITOR_IDENTIFIED = "VISITOR_IDENTIFIED"
    PDF_GENERATION_ALLOWED = "PDF_GENERATION_ALLOWED"
    PDF_GENERATION_BLOCKED = "PDF_GENERATION_BLOCKED"
    FREE_LIMIT_REACHED = "FREE_LIMIT_REACHED"
    COOKIE_MISSING = "COOKIE_MISSING"
    NEW_FINGERPRINT_LINKED = "NEW_FINGERPRINT_LINKED"
    NEW_SESSION_LINKED = "NEW_SESSION_LINKED"
    MULTIPLE_SESSIONS_DETECTED = "MULTIPLE_SESSIONS_DETECTED"
    VISITOR_BLOCKED = "VISITOR_BLOCKED"
    ADMIN_VIEWED_FRAUD_SUMMARY = "ADMIN_VIEWED_FRAUD_SUMMARY"
    ADMIN_VIEWED_VISITOR_PROFILE = "ADMIN_VIEWED_VISITOR_PROFILE"

    NEW_IP_FOR_FINGERPRINT = "NEW_IP_FOR_FINGERPRINT"
    COOKIE_MISSING_BUT_FINGERPRINT_MATCHED = "COOKIE_MISSING_BUT_FINGERPRINT_MATCHED"
    LOCAL_STORAGE_CHANGED = "LOCAL_STORAGE_CHANGED"
    SESSION_CHANGED = "SESSION_CHANGED"
    MULTIPLE_IPS_DETECTED = "MULTIPLE_IPS_DETECTED"
    TOO_MANY_SESSIONS = "TOO_MANY_SESSIONS"
    VPN_PROXY_SUSPECTED = "VPN_PROXY_SUSPECTED"
    BLOCKED_VISITOR_REQUEST = "BLOCKED_VISITOR_REQUEST"
    SUSPICIOUS_REIDENTIFICATION = "SUSPICIOUS_REIDENTIFICATION"


class FraudSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AdminAuditAction(StrEnum):
    ADMIN_VIEWED_FRAUD_EVENTS = "ADMIN_VIEWED_FRAUD_EVENTS"
    ADMIN_VIEWED_FRAUD_VISITORS = "ADMIN_VIEWED_FRAUD_VISITORS"
    ADMIN_VIEWED_FRAUD_SUMMARY = "ADMIN_VIEWED_FRAUD_SUMMARY"
    ADMIN_VIEWED_VISITOR_INVESTIGATION = "ADMIN_VIEWED_VISITOR_INVESTIGATION"
    ADMIN_VIEWED_ALL_PDFS = "ADMIN_VIEWED_ALL_PDFS"
    ADMIN_VIEWED_AUDIT_LOGS = "ADMIN_VIEWED_AUDIT_LOGS"
