from enum import StrEnum


FRAUD_EVENTS_COLLECTION = "fraud_events"
BLOCKED_ENTITIES_COLLECTION = "blocked_entities"


class FraudEventType(StrEnum):
    VISITOR_IDENTIFIED = "VISITOR_IDENTIFIED"
    PDF_GENERATION_ALLOWED = "PDF_GENERATION_ALLOWED"
    PDF_GENERATION_BLOCKED = "PDF_GENERATION_BLOCKED"
    COOKIE_MISSING = "COOKIE_MISSING"
    NEW_FINGERPRINT_LINKED = "NEW_FINGERPRINT_LINKED"
    NEW_SESSION_LINKED = "NEW_SESSION_LINKED"
    MULTIPLE_SESSIONS_DETECTED = "MULTIPLE_SESSIONS_DETECTED"
    VISITOR_BLOCKED = "VISITOR_BLOCKED"
    ADMIN_VIEWED_FRAUD_SUMMARY = "ADMIN_VIEWED_FRAUD_SUMMARY"
    ADMIN_VIEWED_VISITOR_PROFILE = "ADMIN_VIEWED_VISITOR_PROFILE"
    NEW_IP_FOR_FINGERPRINT = "NEW_IP_FOR_FINGERPRINT"
    COOKIE_MISSING_BUT_FINGERPRINT_MATCHED = "COOKIE_MISSING_BUT_FINGERPRINT_MATCHED"
    LOCAL_STORAGE_CHANGED = "LOCAL_STORAGE_CHANGED"
    SESSION_CHANGED = "SESSION_CHANGED"
    MULTIPLE_IPS_DETECTED = "MULTIPLE_IPS_DETECTED"
    TOO_MANY_SESSIONS = "TOO_MANY_SESSIONS"
    VPN_PROXY_SUSPECTED = "VPN_PROXY_SUSPECTED"
    FREE_LIMIT_REACHED = "FREE_LIMIT_REACHED"
    BLOCKED_VISITOR_REQUEST = "BLOCKED_VISITOR_REQUEST"
    SUSPICIOUS_REIDENTIFICATION = "SUSPICIOUS_REIDENTIFICATION"
    RISK_SCORE_UPDATED = "RISK_SCORE_UPDATED"
    AUTOMATION_SIGNAL_DETECTED = "AUTOMATION_SIGNAL_DETECTED"
    HEADLESS_BROWSER_SUSPECTED = "HEADLESS_BROWSER_SUSPECTED"
    API_ONLY_USAGE_PATTERN = "API_ONLY_USAGE_PATTERN"
    RAPID_GENERATION_ATTEMPT = "RAPID_GENERATION_ATTEMPT"
    VPN_PROXY_DETECTED = "VPN_PROXY_DETECTED"
    IDENTITY_LINK_CREATED = "IDENTITY_LINK_CREATED"
    ACCOUNT_FARMING_SUSPECTED = "ACCOUNT_FARMING_SUSPECTED"


class FraudSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class BlockedEntityType(StrEnum):
    FINGERPRINT = "FINGERPRINT"
    IP = "IP"
    COOKIE = "COOKIE"
    LOCAL_STORAGE = "LOCAL_STORAGE"
    VISITOR = "VISITOR"
