from enum import StrEnum


VISITOR_IDENTITY_LINKS_COLLECTION = "visitor_identity_links"


class IdentityLinkType(StrEnum):
    """
    Model describing the identity link type domain object.
    """
    COOKIE_MATCH = "COOKIE_MATCH"
    LOCAL_STORAGE_MATCH = "LOCAL_STORAGE_MATCH"
    FINGERPRINT_MATCH = "FINGERPRINT_MATCH"
    DEVICE_PROFILE_MATCH = "DEVICE_PROFILE_MATCH"
    CANVAS_HASH_MATCH = "CANVAS_HASH_MATCH"
    WEBGL_HASH_MATCH = "WEBGL_HASH_MATCH"
    SESSION_PATTERN_MATCH = "SESSION_PATTERN_MATCH"
    IP_USER_AGENT_MATCH = "IP_USER_AGENT_MATCH"
    ACCOUNT_LINK = "ACCOUNT_LINK"
    ADMIN_MANUAL_LINK = "ADMIN_MANUAL_LINK"
