/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminVisitorsRouteImport } from './routes/admin.visitors'
import { Route as AdminPdfsRouteImport } from './routes/admin.pdfs'
import { Route as AdminMlRouteImport } from './routes/admin.ml'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminVisitorVisitorIdRouteImport } from './routes/admin.visitor.$visitorId'
import { Route as AdminMlModelsRouteImport } from './routes/admin.ml.models'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVisitorsRoute = AdminVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPdfsRoute = AdminPdfsRouteImport.update({
  id: '/pdfs',
  path: '/pdfs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMlRoute = AdminMlRouteImport.update({
  id: '/ml',
  path: '/ml',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisitorVisitorIdRoute = AdminVisitorVisitorIdRouteImport.update({
  id: '/visitor/$visitorId',
  path: '/visitor/$visitorId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMlModelsRoute = AdminMlModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminMlRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/ml': typeof AdminMlRouteWithChildren
  '/admin/pdfs': typeof AdminPdfsRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/ml/models': typeof AdminMlModelsRoute
  '/admin/visitor/$visitorId': typeof AdminVisitorVisitorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/ml': typeof AdminMlRouteWithChildren
  '/admin/pdfs': typeof AdminPdfsRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/ml/models': typeof AdminMlModelsRoute
  '/admin/visitor/$visitorId': typeof AdminVisitorVisitorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/ml': typeof AdminMlRouteWithChildren
  '/admin/pdfs': typeof AdminPdfsRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/ml/models': typeof AdminMlModelsRoute
  '/admin/visitor/$visitorId': typeof AdminVisitorVisitorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/login'
    | '/admin/ml'
    | '/admin/pdfs'
    | '/admin/visitors'
    | '/admin/ml/models'
    | '/admin/visitor/$visitorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/login'
    | '/admin/ml'
    | '/admin/pdfs'
    | '/admin/visitors'
    | '/admin/ml/models'
    | '/admin/visitor/$visitorId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/login'
    | '/admin/ml'
    | '/admin/pdfs'
    | '/admin/visitors'
    | '/admin/ml/models'
    | '/admin/visitor/$visitorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/visitors': {
      id: '/admin/visitors'
      path: '/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AdminVisitorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pdfs': {
      id: '/admin/pdfs'
      path: '/pdfs'
      fullPath: '/admin/pdfs'
      preLoaderRoute: typeof AdminPdfsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ml': {
      id: '/admin/ml'
      path: '/ml'
      fullPath: '/admin/ml'
      preLoaderRoute: typeof AdminMlRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visitor/$visitorId': {
      id: '/admin/visitor/$visitorId'
      path: '/visitor/$visitorId'
      fullPath: '/admin/visitor/$visitorId'
      preLoaderRoute: typeof AdminVisitorVisitorIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ml/models': {
      id: '/admin/ml/models'
      path: '/models'
      fullPath: '/admin/ml/models'
      preLoaderRoute: typeof AdminMlModelsRouteImport
      parentRoute: typeof AdminMlRoute
    }
  }
}

interface AdminMlRouteChildren {
  AdminMlModelsRoute: typeof AdminMlModelsRoute
}

const AdminMlRouteChildren: AdminMlRouteChildren = {
  AdminMlModelsRoute: AdminMlModelsRoute,
}

const AdminMlRouteWithChildren =
  AdminMlRoute._addFileChildren(AdminMlRouteChildren)

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMlRoute: typeof AdminMlRouteWithChildren
  AdminPdfsRoute: typeof AdminPdfsRoute
  AdminVisitorsRoute: typeof AdminVisitorsRoute
  AdminVisitorVisitorIdRoute: typeof AdminVisitorVisitorIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMlRoute: AdminMlRouteWithChildren,
  AdminPdfsRoute: AdminPdfsRoute,
  AdminVisitorsRoute: AdminVisitorsRoute,
  AdminVisitorVisitorIdRoute: AdminVisitorVisitorIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
