from datetime import timedelta
from typing import Any

from fastapi import HTTPException, Request, status
from jose import JWTError, jwt
from passlib.context import CryptContext

from app.config import get_settings
from app.repositories.user_repository import UserRepository
from app.utils.security import utc_now

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


def hash_password(password: str) -> str:
    """
    Hash a plaintext password for persistent storage.

    Args:
        password: Plaintext password provided by the user.

    Returns:
        Secure password hash generated by Passlib.
    """
    return pwd_context.hash(password)


def verify_password(plain_password: str, password_hash: str) -> bool:
    """
    Verify a plaintext password against a stored hash.

    Args:
        plain_password: User-provided plaintext password.
        password_hash: Stored password hash from persistence.

    Returns:
        True when the plaintext password matches the hash.
    """
    return pwd_context.verify(plain_password, password_hash)


def create_access_token(
    subject: str,
    expires_minutes: int | None = None,
    role: str | None = None,
) -> str:
    """
    Create a signed access token for the supplied subject.

    Args:
        subject: User identifier stored in the token subject claim.
        expires_minutes: Optional access token lifetime override.
        role: Optional role claim to embed in the token.

    Returns:
        Signed JWT access token string.
    """
    settings = get_settings()
    expires_delta = timedelta(
        minutes=expires_minutes
        if expires_minutes is not None
        else settings.ACCESS_TOKEN_EXPIRE_MINUTES
    )
    payload = {
        "sub": subject,
        "exp": utc_now() + expires_delta,
        "type": "access",
    }
    if role:
        payload["role"] = role
    return jwt.encode(
        payload,
        settings.JWT_SECRET_KEY,
        algorithm=settings.JWT_ALGORITHM,
    )


def decode_access_token(token: str) -> dict[str, Any]:
    """
    Decode and validate a signed access token.

    Args:
        token: JWT access token received from the client.

    Returns:
        Decoded JWT payload.

    Raises:
        HTTPException: If the token is invalid or missing required claims.
    """
    settings = get_settings()
    try:
        payload = jwt.decode(
            token,
            settings.JWT_SECRET_KEY,
            algorithms=[settings.JWT_ALGORITHM],
        )
    except JWTError as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid authentication token.",
        ) from exc

    if payload.get("type") != "access" or not payload.get("sub"):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid authentication token.",
        )
    return payload


def decode_token_unverified_type(token: str) -> dict[str, Any]:
    """
    Decode a JWT without enforcing the custom access-token type check.

    Args:
        token: JWT token to decode.

    Returns:
        Decoded JWT payload.

    Raises:
        HTTPException: If the token cannot be decoded.
    """
    settings = get_settings()
    try:
        return jwt.decode(
            token,
            settings.JWT_SECRET_KEY,
            algorithms=[settings.JWT_ALGORITHM],
        )
    except JWTError as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid authentication token.",
        ) from exc


def get_authorization_token_optional(request: Request) -> str | None:
    """
    Extract an optional bearer token from the Authorization header.

    Args:
        request: Incoming HTTP request containing authentication headers.

    Returns:
        Bearer token string when present, otherwise None.

    Raises:
        HTTPException: If the Authorization header is malformed.
    """
    authorization = request.headers.get("authorization")
    if not authorization:
        return None

    scheme, _, token = authorization.partition(" ")
    if scheme.lower() != "bearer" or not token:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid Authorization header.",
        )
    return token.strip()


async def get_current_user(request: Request) -> dict[str, Any]:
    """
    Resolve the authenticated user for the current request.

    Args:
        request: Incoming HTTP request carrying the bearer token.

    Returns:
        Active and verified user document.

    Raises:
        HTTPException: If authentication is missing or invalid.
    """
    token = get_authorization_token_optional(request)
    if token is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication token required.",
        )
    return await _load_current_user(token)


async def get_current_user_optional(request: Request) -> dict[str, Any] | None:
    """
    Resolve the authenticated user when a bearer token is present.

    Args:
        request: Incoming HTTP request carrying an optional bearer token.

    Returns:
        Active and verified user document when authenticated, otherwise None.
    """
    token = get_authorization_token_optional(request)
    if token is None:
        return None
    return await _load_current_user(token)


async def _load_current_user(token: str) -> dict[str, Any]:
    """
    Load the current user document from a validated access token.

    Args:
        token: Signed access token to decode and resolve.

    Returns:
        Active and verified user document.

    Raises:
        HTTPException: If the token is invalid or the user is not allowed access.
    """
    payload = decode_access_token(token)
    user = await UserRepository().find_by_id(str(payload["sub"]))
    if user is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid authentication token.",
        )
    if not bool(user.get("is_active", False)):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="User account is disabled.",
        )
    if not bool(user.get("email_verified", user.get("is_verified", False))):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Please verify your email to continue.",
        )
    return user
